spring:
    datasource:
        url: jdbc:h2:mem:nfl
        username: ${H2_USERNAME:sa}
        password: ${H2_PASSWORD:password}
        driverClassName: org.h2.Driver
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect